### ISSUE TITLE
gitlog plugin is failing if we do shallow clone

### ISSUE THREAD

**Issue by ramkannan2003** [danielflower/maven-gitlog-plugin#29]
Hi,

We are using this plugin in our maven project. As Our repository is very big, we do shallow clone in our Jenkins Job to run Unit Test then update artifact in nexus. But we are getting the following error when we run the maven build after doing shallow clone. 

Failed to execute goal com.github.danielflower.mavenplugins:maven-gitlog-plugin:1.5.0:generate (default) on project stella-webapp: Execution default of goal com.github.danielflower.mavenplugins:maven-gitlog-plugin:1.5.0:generate failed: Walk failure. Missing commit 296bb44b654fa0a1591282812ff7e0b078d96634 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.danielflower.mavenplugins:maven-gitlog-plugin:1.5.0:generate (default) on project stella-webapp: Execution default of goal com.github.danielflower.mavenplugins:maven-gitlog-plugin:1.5.0:generate failed: Walk failure.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.github.danielflower.mavenplugins:maven-gitlog-plugin:1.5.0:generate failed: Walk failure.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more

**Comment by ramkannan2003** [comment]
This issue is resolved after updating the latest version

**Comment by danielflower** [comment]
Oh, that was easy :) Cheers

**Comment by xinaggie** [comment]
Hi, i updated to latest version, still see this error, could you please help?

Error: 4-02 04:30:04] [autobuild] [ERROR] Failed to execute goal com.github.danielflower.mavenplugins:gitlog-maven-plugin:1.14.0:generate (default) on project myproject: Execution default of goal com.github.danielflower.mavenplugins:gitlog-maven-plugin:1.14.0:generate failed: Walk failure. Missing commit 7fa922191b3c30741792099051d7714a2f2115fe -> [Help 1]
  [2023-04-02 04:30:04] [autobuild] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.danielflower.mavenplugins:gitlog-maven-plugin:1.14.0:generate (default) on project booking-events: Execution default of goal com.github.danielflower.mavenplugins:gitlog-maven-plugin:1.14.0:generate failed: Walk failure.
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
  [2023-04-02 04:30:04] [autobuild]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
  [2023-04-02 04:30:04] [autobuild]     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
  [2023-04-02 04:30:04] [autobuild]     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
  [2023-04-02 04:30:04] [autobuild]     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
  [2023-04-02 04:30:04] [autobuild]     at java.lang.reflect.Method.invoke (Method.java:498)
  [2023-04-02 04:30:04] [autobuild]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
  [2023-04-02 04:30:04] [autobuild]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
  [2023-04-02 04:30:04] [autobuild]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
  [2023-04-02 04:30:04] [autobuild]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
